AusprintCM-war/src/ausprinting/cm/mbeans/CustomerManagedBean.java
package ausprinting.cm.mbeans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
//import javax.enterprise.context.ApplicationScoped;
//import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
//import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import ausprinting.cm.repository.ContactPersonRepository;
import ausprinting.cm.repository.CustomerRepository;
import ausprinting.cm.repository.entities.Address;
import ausprinting.cm.repository.entities.ContactPerson;
import ausprinting.cm.repository.entities.Customer;
import ausprinting.cm.repository.entities.Industry;


@ManagedBean(name = "customerManagedBean")
@SessionScoped
public class CustomerManagedBean implements Serializable{
	
	// @EJB: Injects a reference of the local, remote, or no-interface view of an EJB into the annotated variable.
	@EJB
	CustomerRepository customerRepository;
	
	@PostConstruct
	public void init() {
		Customer customer = new Customer();
		customer.setCustomerId(1);
		searchCustomerById(customer.getCustomerId());
		
	}

	/**
	 * Creates a new instance of CustomerManagedBean
	 */
	
	public CustomerManagedBean() {
		
	}
	
	// =====================Customer=================
	
	/**
	 * Add a new customer
	 * @param customer
	 */
	public void addCustomer(Customer customer) {
		try {
			customerRepository.addCustomer(customer);
		} catch (Exception ex) {
			Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer cannot be added!"));
		}
	}
	
	
	/**
	 * Search a customer by Id
	 * @throws Exception 
	 * 
	 */
	public Customer searchCustomerById(int id) throws NullPointerException {
			try {
				return customerRepository.searchCustomerById(id);
			} catch (Exception e) {
				Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, e);
	    		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("The customer id does not exist, please enter a valid id 2"));
			}
			return null;
	}
	
	
	/**
	 *  Question
	 *  
	 * @param customer
	 */
    
	public void editCustomer(Customer customer) throws NullPointerException{
		try {
			String s = customer.getAddress().getStreetNumber();
			Address address = customer.getAddress();
			address.setStreetNumber(s);
			customer.setAddress(address);
			
			customerRepository.editCustomer(customer);
			
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer has been updated succesfully"));
		} catch (Exception ex) {
			Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	
	public void removeCustomer(int customerId) throws NullPointerException {
		try {
			customerRepository.removeCustomer(customerId);
		} catch (Exception ex) {
			Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Unable to remove customer return at CustomerManagedBean!"));
		}
	}
	
	
	// CHANGED for nullPointerException
	public List<Customer> getAllCustomers() throws Exception {
		List<Customer> customers = customerRepository.getAllCustomers();
		return customers;
	}
	
	
	// This is used for calling the entity manager to search the customer by customerName
    public List<Customer> searchCustomerByName(String name) {
        try {
            return customerRepository.searchCustomerByName(name);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
	
    
	public void addLocalCustomer(ausprinting.cm.controllers.Customer localCustomer) {
		// convert this newCustomer which is the local customer to entity customer
		Customer customer = convertCustomerToEntity(localCustomer);
		
		try {
			customerRepository.addCustomer(customer);
		} catch (Exception ex) {
			Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Unable to convert and add localCustomer!"));
		}
	}
	
	
	// Convert customer to entity
	public Customer convertCustomerToEntity(ausprinting.cm.controllers.Customer localCustomer) {
		Customer customer = new Customer(); //Entity
		
		
		// Address attributes
        String streetNumber = localCustomer.getStreetNumber();
        String streetAddress = localCustomer.getStreetAddress();
        String suburb = localCustomer.getSuburb();
        String postcode = localCustomer.getPostcode();
        String state = localCustomer.getState();
        String country = localCustomer.getCountry();
        
        
        // Customer attributes
        String customerName = localCustomer.getCustomerName();
        String customerPhoneNumber = localCustomer.getcustomerPhoneNumber();
        String email = localCustomer.getEmail();
        int customerId = localCustomer.getCustomerId();
        
        // Industry attribute
        // Industry industry = new ausprinting.cm.repository.entities.Industry();
        
        
//        // ContactPerson attributes//bug
//        int contactPersonId = localCustomer.getContactPersonId();
//        // name refers to contactPerson name
//        String contactPersonName = localCustomer.getContactPersonName();
//        String phoneNumber = localCustomer.getPhoneNumber();
//        String contactPersonEmail = localCustomer.getContactPersonEmail();
        
        
        // Set address attributes to Address object
        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state, country);
        
        
//        // Set contact person attributes
//        ContactPerson contactPerson = new ausprinting.cm.repository.entities.ContactPerson(contactPersonId, contactPersonName, phoneNumber, contactPersonEmail);
//		if (contactPerson.getContactPersonId() == 0){
//			contactPerson = null;
//		}
		

        // Set customer attributes
        customer.setAddress(address);
        customer.setCustomerName(customerName);
        customer.setcustomerPhoneNumber(customerPhoneNumber);
        customer.setEmail(email);
        customer.setIndustry(localCustomer.getIndustry());
        customer.setCustomerId(customerId);
        customer.setTags(localCustomer.getTags());
        customer.setContactPerson(localCustomer.getContactPerson());
        
        
		return customer;
	}
	
	
	// ==================Contact Person================
	
	
    public List<ContactPerson> getAllContactPeople() throws Exception {
        try {
            return customerRepository.getAllContactPeople();
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    // Search Customer by contactPersonId
	public Set<Customer> searchCustomerByContactPersonId(int contactPersonId) {
		try {
            //retrieve contact person by id
            for (ContactPerson contactPerson : customerRepository.getAllContactPeople()) {
                if (contactPerson.getContactPersonId() == contactPersonId) {
                    return customerRepository.searchCustomerByContactPerson(contactPerson);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
	}
	
	// ==================Industry================
	
	public List<Industry> getAllIndustries() throws Exception {
		try {
			return customerRepository.getAllIndustries();
		} catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		return null;
	}


	
}

AusprintCM-war/WebContent/staff/add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-dark bg-dark" style="background-color: #000000;">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add Customer
                </div>
            </div>
        <div>
	        <f:view>
	            <h:form>
	                <h1><h:outputText value="Create"/></h1>
	                <table class="table table-bordered ">
	                
	                    <tr class="#{!streetNumber.valid ? 'has-error' : 'none'}">
	                        <td width ="200">
	                            <h:outputLabel value="streetNumber" for="streetNumber" />
	                        </td>
	                        <td>
	                            <h:inputText id="streetNumber" value="#{customer.streetNumber}" title="streetNumber" required="true" requiredMessage="Please enter the street number!" validatorMessage="Please enter a street number between 1 and 1000" converterMessage="Please enter a number" pt:placeholder="900">
		                            <f:convertNumber integerOnly="true"/>
									<f:validateLongRange minimum="1" maximum="1000" /> 
								</h:inputText>
	                            <br/>
	                            <h:message for="streetNumber" class="#{!streetNumber.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    </tr>
	
	                    <tr class="#{!streetAddress.valid ? 'has-error' : 'none'}">
	                        <td>
	                            <h:outputLabel value="streetAddress" for="streetAddress" />
	                        </td>
	                        <td>
	                            <h:inputText id="streetAddress" value="#{customer.streetAddress}" title="streetAddress" required="true" requiredMessage="Please enter the street address!" pt:placeholder="Dandenong Rd"/>
	                            <br/>
	                            <h:message for="streetAddress" class="#{!streetAddress.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    
	                    </tr>
	                    
	                    <tr class="#{!suburb.valid ? 'has-error' : 'none'}">
	                        <td>
	                            <h:outputLabel value="suburb" for="suburb" />
	                        </td>
	                        <td>
	                            <h:inputText id="suburb" value="#{customer.suburb}" title="suburb" required="true" requiredMessage="Please enter the suburb!" pt:placeholder="Caulfield East"/>
	                        	<br/>
	                            <h:message for="suburb" class="#{!suburb.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    
	                    </tr>
	                    
	                    <tr class="#{!state.valid ? 'has-error' : 'none'}">
	                        <td>
	                            <h:outputLabel value="state" for="state"/>
	                        </td>
	                        <td>
	                            <h:inputText id="state" value="#{customer.state}" title="state" size="3" required="true" requiredMessage="Please enter the state!" pt:placeholder="VIC"/>
	                            <br/>
	                            <h:message for="state" class="#{!state.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    
	                    </tr>
	                    
	                    <tr class="#{!country.valid ? 'has-error' : 'none'}">
	                        <td>
	                            <h:outputLabel value="country" for="country"/>
	                        </td>
	                        <td>
	                            <h:inputText id="country" value="#{customer.country}" title="country" size="3" required="true" requiredMessage="Please enter the country" pt:placeholder="Australia"/>
	                            <br/>
	                            <h:message for="country" class="#{!country.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    
	                    </tr>
	                    
	                    
	                    <tr class="#{!postcode.valid ? 'has-error' : 'none'}">
	                        <td>
	                            <h:outputLabel value="postcode" for="postcode" />
	                        </td>
	                        <td>
	                            <h:inputText id="postcode" value="#{customer.postcode}" title="postcode" required="true" requiredMessage="Please enter the postcode!" validatorMessage="Please enter a postcode between 0200 and 4700" converterMessage="Please enter a number" pt:placeholder="3145">
		                            <f:convertNumber integerOnly="true"/>
									<f:validateLongRange minimum="200" maximum="4700" /> 
								</h:inputText>
								<br/>
								<h:message for="postcode" class="#{!postcode.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    
	                    </tr>
	
	                    <tr class="#{!customerName.valid ? 'has-error' : 'none'}">
	                        <td>
	                            <h:outputLabel value="customerName" for="customerName"/>
	                        </td>
	                        <td>
	                            <h:inputText id="customerName" value="#{customer.customerName}" title="Customer Name" required="true" requiredMessage="Please enter the name of customer!"  pt:placeholder="Apple">
	                            </h:inputText>
	                           	<br/>
	                           	<h:message for="customerName" class="#{!customerName.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    
	                    </tr>
	                    
	                    <tr class="#{!customerPhoneNumber.valid ? 'has-error' : 'none'}">
	                        <td>
	                            <h:outputLabel value="customerPhoneNumber" for="customerPhoneNumber" />
	                        </td>
	                        <td>
	                            <h:inputText id="customerPhoneNumber" value="#{customer.customerPhoneNumber}" title="Phone Number" required="true" requiredMessage="Please enter the Phone Number!" validatorMessage="Please enter a 10 digits phone number" pt:placeholder="0123456789">
		                            <!-- Validate the phone number to be 10 characters -->
									<f:validateLength minimum="10" maximum="10" /> 
								</h:inputText>
								<br/>
								<h:message for="customerPhoneNumber" class="#{!customerPhoneNumber.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    
	                    </tr>
	
	                    <tr class="#{!email.valid ? 'has-error' : 'none'}">
	                        <td>
	                            <h:outputLabel value="Email" for="Email" />
	                        </td>
	                        <td>
	                            <h:inputText id="Email" value="#{customer.email}" title="Email" required="true" requiredMessage="Please enter an Email!" pt:placeholder="john@monash.edu">
		                        </h:inputText>
								<br/>
								<h:message for="Email" class="#{!email.valid ? 'label label-warning' : 'none'}" />
	                        </td>
	                    
	                    </tr>
	                    
	                    
	                    <!-- Select and Add Industry -->
	                     <tr>
							<td>
	                            <h:outputLabel value="Industry" for="industry" />
	                        </td>
	                        <td>
			                    <h:selectOneMenu value="#{customer.industry}" converter="industry"> 
	   								<f:selectItems value="#{customerManagedBean.allIndustries}" var="i" itemLabel="#{i.industryName}" itemValue="#{i}"/>
								</h:selectOneMenu>
							</td>          
	                    </tr>
	                    
	
	                    <!-- Select and Add contactPerson -->
	                    
	  					<tr>
							<td>
	                            <h:outputLabel value="contactPerson" for="contactPerson" />
	                        </td>
	                        <td>
			                    <h:selectOneMenu value="#{customer.contactPerson}" converter="contactPerson"> 
	   								<f:selectItems value="#{customerApplication.contactPeople}" var="c" itemLabel="#{c.contactPersonName}" itemValue="#{c}"/>
								</h:selectOneMenu>  
							</td>          
	                    </tr>
	                    <!-- customerApplication.customers.get(status.index).customerName -->
	                    
	                    
	                    <!-- Testing Method -->
	                    
	                    
	                </table>
	                
	                <h:commandButton id="submit" value="Submit" action="#{addCustomer.addCustomer(customer)}" class="btn btn-default" >
	                </h:commandButton>
	                <h:link id="close" value="Close" outcome="/faces/staff/index.xhtml"
							class="btn btn-default" />
	            </h:form>	
	        </f:view>
        </div>
       </div>
    </h:body>
</html>

AusprintCM-war/WebContent/staff/addContactPerson.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
	<h:head>
		<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
		<h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
		<title>#{titleController.pageTitle}</title> 
	</h:head>
	<h:body>
		<div class="container">
            <div class="navbar navbar-dark bg-dark" style="background-color: #000000;">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add Contact Person
                </div>
            </div>
		    <div>
	        	<f:view>
	            	<h:form>
		                <h1><h:outputText value="Create"/></h1>
		                <table class="table table-bordered ">
		
		                    <tr class="#{!contactPersonName.valid ? 'has-error' : 'none'}">
		                        <td>
		                            <h:outputLabel value="contactPersonName" for="contactPersonName"/>
		                        </td>
		                        <td>
		                            <h:inputText id="contactPersonName" value="#{contactPerson.contactPersonName}" title="Staff Name" required="true" requiredMessage="Please enter the name of staff!"  pt:placeholder="Andy Liu">
		                            </h:inputText>
		                           	<br/>
		                           	<h:message for="contactPersonName" class="#{!contactPersonName.valid ? 'label label-warning' : 'none'}" />
		                        </td>
		                    
		                    </tr>
		                    
		                    <tr class="#{!phoneNumber.valid ? 'has-error' : 'none'}">
		                        <td>
		                            <h:outputLabel value="phoneNumber" for="phoneNumber" />
		                        </td>
		                        <td>
		                            <h:inputText id="phoneNumber" value="#{contactPerson.phoneNumber}" title="Phone Number" required="true" requiredMessage="Please enter the Phone Number!" validatorMessage="Please enter a 10 digits phone number" pt:placeholder="0123456789">
			                            <!-- Validate the phone number to be 10 characters -->
										<f:validateLength minimum="10" maximum="10" /> 
									</h:inputText>
									<br/>
									<h:message for="phoneNumber" class="#{!phoneNumber.valid ? 'label label-warning' : 'none'}" />
		                        </td>
		                    
		                    </tr>
		
		                    <tr class="#{!email.valid ? 'has-error' : 'none'}">
		                        <td>
		                            <h:outputLabel value="Email" for="Email" />
		                        </td>
		                        <td>
		                            <h:inputText id="Email" value="#{contactPerson.contactPersonEmail}" title="Email" required="true" requiredMessage="Please enter an Email!" pt:placeholder="staff1@ausprinting.com">
			                        </h:inputText>
									<br/>
									<h:message for="Email" class="#{!email.valid ? 'label label-warning' : 'none'}" />
		                        </td>
		                    
		                    </tr>
	                	</table>
	                	<div>
	                		<h:commandButton id="submit" value="Submit" action="#{addContactPerson.addContactPerson(contactPerson)}" class="btn btn-default" >
                			</h:commandButton>
                			<h:link id="close" value="Close" outcome="/faces/staff/indexContactPerson.xhtml" class="btn btn-default" />
	                	</div>
		                
	            	</h:form>
	        	</f:view>
			</div>
		</div>
	</h:body>
</html>

AusprintCM-war/WebContent/staff/edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"      
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="style.css" />
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-dark bg-dark" style="background-color: #000000;">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Edit Customer
                </div>
            </div>
			
            <h:form id="MyForm">
                <table class="table table-bordered ">
                    <tr>
                        <td width ="150" valign="top">Id:</td>
                        
                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{customerController.customer.customerId}</h:outputLabel>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Street number: </td>
                         Edit Customer Details
                        <td valign="bottom">
                            <h:inputText id = "streetNumber" value="#{customerController.customer.address.streetNumber}" binding="#{streetNumber}" required="true"
                                         validatorMessage="Please enter a valid street number."
                                         requiredMessage="Please enter an street number. "></h:inputText>    
                        </td>
                    </tr>
                    
                    
                    <tr>
                        <td width ="100" valign="top">Street address: </td>
                        <td valign="bottom">
                            <h:inputText id = "streetAddress" value="#{customerController.customer.address.streetAddress}" binding="#{streetAddress}" required="true"
                                         validatorMessage="Please enter a valid street address."
                                         requiredMessage="Please enter an street address. "></h:inputText>    
                        </td>
                    </tr>
                    
                    <tr>
                        <td width ="100" valign="top">Suburb: </td>
                        <td valign="bottom">
                            <h:inputText id = "suburb" value="#{customerController.customer.address.suburb}" binding="#{suburb}" required="true"
                                         validatorMessage="Please enter a valid suburb."
                                         requiredMessage="Please enter a suburb. "></h:inputText>    
                        </td>
                    </tr>
                    
                    <tr>
                        <td width ="100" valign="top">State: </td>
                        <td valign="bottom">
                            <h:inputText id = "state" value="#{customerController.customer.address.state}" binding="#{state}" required="true"
                                         validatorMessage="Please enter a valid state."
                                         requiredMessage="Please enter a state. "></h:inputText>    
                        </td>
                    </tr>
                    
                    <tr>
                        <td width ="100" valign="top">Country: </td>
                        <td valign="bottom">
                            <h:inputText id = "country" value="#{customerController.customer.address.country}" binding="#{country}" required="true"
                                         validatorMessage="Please enter a valid country."
                                         requiredMessage="Please enter a country. "></h:inputText>    
                        </td>
                    </tr>
                    
                    <tr>
                        <td width ="100" valign="top">Postcode: </td>
                        <td valign="bottom">
                            <h:inputText id = "postcode" value="#{customerController.customer.address.postcode}" binding="#{postcode}" required="true"
                                         validatorMessage="Please enter a valid integer postcode."
                                         requiredMessage="Please enter a postcode.">
                                         <f:validateLongRange minimum="100" maximum="9999" />
                            </h:inputText>    
                        </td>
                    </tr>
                    
                    
                    <tr>
                        <td width ="100" valign="top">Customer Name: </td>
                        
                        <td valign="bottom">
                            <h:inputText id = "customerName" value="#{customerController.customer.customerName}"  required="true"
                                         requiredMessage="Please enter a customer's name.">
                            </h:inputText>    
                    	</td>
                    </tr>
                    
                    <tr>
                        <td width ="100" valign="top">Phone number: </td>
                        
                        <td valign="bottom">
                            <h:inputText id = "customerPhoneNumber" value="#{customerController.customer.customerPhoneNumber}"  required="true" validatorMessage="Phone number must be integer" requiredMessage="Please enter phone number. ">
                            	<f:convertNumber integerOnly="true"/>
                            	<f:validateLongRange minimum="0000000000" maximum="9999999999" />
                            </h:inputText>    
                        </td>
                    </tr>
                    
                    <tr>
                        <td width ="100" valign="top">Email: </td>
                        
                        <td valign="bottom">
                            <h:inputText id = "Email" value="#{customerController.customer.email}"  required="true"
                                         requiredMessage="Please enter an email. ">
                            </h:inputText>     
                        </td>
                        
                    </tr>
                    
                    <!-- Select and Add Industry -->
                    <tr>
						<td>
                            <h:outputLabel value="Industry" for="industry" />
                        </td>
                        <td>
		                    <h:selectOneMenu value="#{customerController.customer.industry}" converter="industry"> 
   								<f:selectItems value="#{customerManagedBean.allIndustries}" var="i" itemLabel="#{i.industryName}" itemValue="#{i}"/>
							</h:selectOneMenu>
						</td>          
                    </tr>
                    
                    <!-- Select and Add contactPerson-->
                    <tr>
						<td>
                            <h:outputLabel value="contactPerson" for="contactPerson" />
                        </td>
                        <td>
		                    <h:selectOneMenu value="#{customerController.customer.contactPerson}" converter="contactPerson"> 
   								<f:selectItems value="#{customerApplication.contactPeople}" var="c" itemLabel="#{c.contactPersonName}" itemValue="#{c}"/>
							</h:selectOneMenu>  
						</td>          
                    </tr>
                    
                </table>
                
                <h:commandButton id="save" value="Save" action="#{customerManagedBean.editCustomer(customerController.customer)}"  class="btn btn-default" >
                    <f:param name="customerID" value="#{customerController.customerId+1}"/>
                </h:commandButton>
                <h:link id="close" value="Close" outcome="/faces/staff/index.xhtml"
						class="btn btn-default" />
            </h:form>
        </div>
    </h:body>
</html>