AusprintCM-war/src/ausprinting/cm/mbeans/CustomerManagedBean.java
package ausprinting.cm.mbeans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
//import javax.enterprise.context.ApplicationScoped;
//import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
//import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import ausprinting.cm.repository.ContactPersonRepository;
import ausprinting.cm.repository.CustomerRepository;
import ausprinting.cm.repository.entities.Address;
import ausprinting.cm.repository.entities.ContactPerson;
import ausprinting.cm.repository.entities.Customer;
import ausprinting.cm.repository.entities.Industry;


@ManagedBean(name = "customerManagedBean")
@SessionScoped
public class CustomerManagedBean implements Serializable{
	
	// @EJB: Injects a reference of the local, remote, or no-interface view of an EJB into the annotated variable.
	@EJB
	CustomerRepository customerRepository;
	
	@PostConstruct
	public void init() {
		Customer customer = new Customer();
		customer.setCustomerId(1);
		searchCustomerById(customer.getCustomerId());
		
	}

	/**
	 * Creates a new instance of CustomerManagedBean
	 */
	
	public CustomerManagedBean() {
		
	}
	
	// =====================Customer=================
	
	/**
	 * Add a new customer
	 * @param customer
	 */
	public void addCustomer(Customer customer) {
		try {
			customerRepository.addCustomer(customer);
		} catch (Exception ex) {
			Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer cannot be added!"));
		}
	}
	
	
	/**
	 * Search a customer by Id
	 * @throws Exception 
	 * 
	 */
	public Customer searchCustomerById(int id) throws NullPointerException {
			try {
				return customerRepository.searchCustomerById(id);
			} catch (Exception e) {
				Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, e);
	    		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("The customer id does not exist, please enter a valid id 2"));
			}
			return null;
	}
	
	
	/**
	 *  Question
	 *  
	 * @param customer
	 */
    
	public void editCustomer(Customer customer) throws NullPointerException{
		try {
			String s = customer.getAddress().getStreetNumber();
			Address address = customer.getAddress();
			address.setStreetNumber(s);
			customer.setAddress(address);
			
			customerRepository.editCustomer(customer);
			
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer has been updated succesfully"));
		} catch (Exception ex) {
			Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	
	public void removeCustomer(int customerId) throws NullPointerException {
		try {
			customerRepository.removeCustomer(customerId);
		} catch (Exception ex) {
			Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Unable to remove customer return at CustomerManagedBean!"));
		}
	}
	
	
	// CHANGED for nullPointerException
	public List<Customer> getAllCustomers() throws Exception {
		List<Customer> customers = customerRepository.getAllCustomers();
		return customers;
	}
	
	
	// This is used for calling the entity manager to search the customer by customerName
    public List<Customer> searchCustomerByName(String name) {
        try {
            return customerRepository.searchCustomerByName(name);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
	
    
	public void addLocalCustomer(ausprinting.cm.controllers.Customer localCustomer) {
		// convert this newCustomer which is the local customer to entity customer
		Customer customer = convertCustomerToEntity(localCustomer);
		
		try {
			customerRepository.addCustomer(customer);
		} catch (Exception ex) {
			Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Unable to convert and add localCustomer!"));
		}
	}
	
	
	// Convert customer to entity
	public Customer convertCustomerToEntity(ausprinting.cm.controllers.Customer localCustomer) {
		Customer customer = new Customer(); //Entity
		
		
		// Address attributes
        String streetNumber = localCustomer.getStreetNumber();
        String streetAddress = localCustomer.getStreetAddress();
        String suburb = localCustomer.getSuburb();
        String postcode = localCustomer.getPostcode();
        String state = localCustomer.getState();
        String country = localCustomer.getCountry();
        
        
        // Customer attributes
        String customerName = localCustomer.getCustomerName();
        String customerPhoneNumber = localCustomer.getcustomerPhoneNumber();
        String email = localCustomer.getEmail();
        int customerId = localCustomer.getCustomerId();
        
        // Industry attribute
        // Industry industry = new ausprinting.cm.repository.entities.Industry();
        
        
//        // ContactPerson attributes//bug
//        int contactPersonId = localCustomer.getContactPersonId();
//        // name refers to contactPerson name
//        String contactPersonName = localCustomer.getContactPersonName();
//        String phoneNumber = localCustomer.getPhoneNumber();
//        String contactPersonEmail = localCustomer.getContactPersonEmail();
        
        
        // Set address attributes to Address object
        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state, country);
        
        
//        // Set contact person attributes
//        ContactPerson contactPerson = new ausprinting.cm.repository.entities.ContactPerson(contactPersonId, contactPersonName, phoneNumber, contactPersonEmail);
//		if (contactPerson.getContactPersonId() == 0){
//			contactPerson = null;
//		}
		

        // Set customer attributes
        customer.setAddress(address);
        customer.setCustomerName(customerName);
        customer.setcustomerPhoneNumber(customerPhoneNumber);
        customer.setEmail(email);
        customer.setIndustry(localCustomer.getIndustry());
        customer.setCustomerId(customerId);
        customer.setTags(localCustomer.getTags());
        customer.setContactPerson(localCustomer.getContactPerson());
        
        
		return customer;
	}
	
	
	// ==================Contact Person================
	
	
    public List<ContactPerson> getAllContactPeople() throws Exception {
        try {
            return customerRepository.getAllContactPeople();
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    // Search Customer by contactPersonId
	public Set<Customer> searchCustomerByContactPersonId(int contactPersonId) {
		try {
            //retrieve contact person by id
            for (ContactPerson contactPerson : customerRepository.getAllContactPeople()) {
                if (contactPerson.getContactPersonId() == contactPersonId) {
                    return customerRepository.searchCustomerByContactPerson(contactPerson);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
	}
	
	// ==================Industry================
	
	public List<Industry> getAllIndustries() throws Exception {
		try {
			return customerRepository.getAllIndustries();
		} catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		return null;
	}


	
}

AusprintCM-war/WebContent/admin/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"  
      xmlns:f="http://java.sun.com/jsf/core"    
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet name="css/style.css" />
        <title>#{titleController.pageTitle}</title>
        <!-- adding navigation bar --> 
		<h:form>
		    <div class="navbar navbar-inverse">
		        <div class="container-fluid">
		            <div class="navbar-header">
		                <button type="button" class="navbar-toggle">
		                    <span class="sr-only">Toggle navigation</span> 
		                    <span class="icon-bar"></span> 
		                    <span class="icon-bar"></span> 
		                    <span class="icon-bar"></span>
		                </button>
		                <a class="navbar-brand" href="index">AusPrinting CM</a>
		            </div>
		            <div class="collapse navbar-collapse" id="myNavbar">
		                <ul class="nav navbar-nav">
		                    <li><a href="index.xhtml">Home</a></li>
		                    <li><a href="indexContactPerson.xhtml">Contact Person</a></li>
		                </ul>
		                <ul class="nav navbar-nav navbar-right">
		                	<li><a href="#">Hello #{request.remoteUser}</a></li>
		                	<!-- Log out -->
		                    <li>
		                        <h:commandLink value="Logout" action="#{userManager.logout()}"></h:commandLink>    
		                    </li>
		                </ul>
		            </div>
		            <!--/.nav-collapse -->
		        </div>
		    </div>
		</h:form>
		<!-- adding navigation bar -->
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Customer List
                </div>
            </div>
			
            <h:form id="MyForm">
                <table class="table table-bordered table-striped table-hover">
                    <!-- For each customer in customers ArrayList... --> 
                    <tr>
                            <td> 
                                <h:outputLabel id="Id" value="Id"  />
                            </td>
                            
                            <td> 
                                <h:outputLabel id="Name" value="Name"  />
                            </td>
                            
                            <td> 
                                <h:outputLabel id="Email" value="Email"/>
                            </td>
                            
                            <td> 
                                <h:outputLabel id="Industry" value="Industry"/>
                            </td>
                            
                            <td> 
                                <h:outputLabel id="PhoneNumber" value="PhoneNumber"/>
                            </td>
          
                            <td> 
                                <h:outputLabel id="Address" value="Address"/>
                            </td>
                            
                            <td> 
                                <h:outputLabel id="ContactPerson" value="Contact Person"/>
                            </td>
                            
                            
                            <td></td>     
                     </tr>
                    
                    <ui:repeat id="Myrepeat" value="#{customerApplication.customers}"  var="customer" varStatus="status"> 
                        <!-- What does the outName do here -->
                        <tr onclick="document.getElementById('MyForm:principle').value = document.getElementById('MyForm:Myrepeat:#{status.index}:outName').textContent"> 
                            <td>
                                <h:outputText value="#{customerApplication.customers.get(status.index).customerId}" id="customerID" /> 
                                
                            </td>
                            
                            <td> 
                                <h:outputText id="outName" value="#{customerApplication.customers.get(status.index).customerName}"  />
                            </td>
                            
                            <td>
                                <h:outputText id="outEmail" value="#{customerApplication.customers.get(status.index).email}"></h:outputText>
                            </td>
                            
                            <td>
                                <h:outputText id="outIndustry" value="#{customerApplication.customers.get(status.index).industry.industryName}"></h:outputText>
                            </td>
                            
                            <td>
                                <h:outputText id="outPhoneNumber" value="#{customerApplication.customers.get(status.index).customerPhoneNumber}"></h:outputText>
                            </td>
                            
                            <td>
                                <h:outputText id="outAddress" value="#{customerApplication.customers.get(status.index).address}"></h:outputText>
                            </td>
                            
                            <td>
                                <h:outputText id="outContactPerson" value="#{customerApplication.customers.get(status.index).contactPerson.contactPersonName}"></h:outputText>
                            </td>
                            
                            <td>
                                <h:link value="View | " outcome="/faces/staff/detail.xhtml">
                                <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
                                  <f:param name="customerID" value="#{status.index + 1}"/>
                                </h:link>

                                <h:link value="Edit | " outcome="/faces/staff/edit.xhtml">
                                <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                  You can get the value from next page using the indexController -->
                                  <f:param name="customerID" value="#{status.index + 1}"/>
                                </h:link>
                                
                                <h:commandLink value="Delete" action="#{removeCustomer.removeCustomer(customerApplication.customers.get(status.index).customerId)}" disabled="#{customerApplication.customers.get(status.index).customerId == null}">
                                </h:commandLink>
                                    
                                <h:outputText value=" "/>
                            </td>
                            
                        </tr> 

                    </ui:repeat> 

                </table>
                
                
                
                <div class="row">
					<div class="col-sm-4">
					<!-- Search Customer by customerId -->
						<h:inputText value="#{searchCustomer.searchByInt}" id="searchById" required="true" onchange ="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} "   /> 
	                    <h:commandButton id="searchId" value="Search Name by Id" action="#{searchCustomer.searchCustomerById(searchCustomer.searchByInt)}" class="btn btn-default" >
	                        <f:param name="customerID" value="#{status.index + 1}"/>
	                        <f:ajax execute="@form" render="ajaxMessage1"/>
	                    </h:commandButton>
					</div>
					<div class="col-sm-4">
					<!-- Search Customer By contactPersonId -->
		                <h:selectOneMenu id="contact" value="#{searchCustomer.contactPersonId}" >
			                <f:selectItems value="#{customerManagedBean.allContactPeople}" var="c"  
			                               itemLabel="#{c.contactPersonName}" itemValue="#{c.contactPersonId}" />
		                </h:selectOneMenu>
		                <h:commandButton id="searchByContact" value="Search by Contact" action="#{searchCustomer.searchCustomerByContactPersonId(searchCustomer.contactPersonId)}" class="btn btn-default" >
		                	<f:param name="customerID" value="#{status.index + 1}"/>
		                	<f:ajax execute="@form" render="MyForm"/>
		                </h:commandButton>
					</div>
					<div class="col-sm-4">
					<!-- Search Customer By name -->
	                    <h:inputText value="#{searchCustomer.searchByName}" id="searchByName" required="false" p:placeholder="Name" /> 
                    	<h:commandButton id="searchName" value="Search by Name" action="#{searchCustomer.searchCustomerByName(searchCustomer.searchByName)}" class="btn btn-default" >
                        	<f:param name="customerID" value="#{status.index + 1}"/>
                        	<f:ajax execute="@form" render="MyForm"/>
                    	</h:commandButton>
					</div>
				</div>
				
                
                <div class="row">
				  	<div class="col-sm-4">
				  		<h:outputText value="#{customerManagedBean.searchCustomerById(searchCustomer.searchByInt).customerName}" id="ajaxMessage1"/>
				  	</div>
				  	<div class="col-sm-4">
					  	<h:commandButton id="viewAll" value="View All" action="#{searchCustomer.searchAllCustomers()}" class="btn btn-default" >
		                	<f:param name="customerID" value="#{status.index + 1}"/>
		                </h:commandButton>
					</div>
				  	<div class="col-sm-4">
				  		<h:commandButton id="add" value="Add" action="add.xhtml" class="btn btn-default" />
                    </div>
				</div>

            </h:form>
        </div>
        <br/>
        <div>
        	<h:message styleClass="color:red; font-weight:bold" globalOnly="true"/>
        </div>
    </h:body>
</html>